/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarsWeatherRouteImport } from './routes/mars-weather'
import { Route as MarsRoverRouteImport } from './routes/mars-rover'
import { Route as ApodRouteImport } from './routes/apod'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const MarsWeatherRoute = MarsWeatherRouteImport.update({
  id: '/mars-weather',
  path: '/mars-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const MarsRoverRoute = MarsRoverRouteImport.update({
  id: '/mars-rover',
  path: '/mars-rover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApodRoute = ApodRouteImport.update({
  id: '/apod',
  path: '/apod',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apod': typeof ApodRoute
  '/mars-rover': typeof MarsRoverRoute
  '/mars-weather': typeof MarsWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apod': typeof ApodRoute
  '/mars-rover': typeof MarsRoverRoute
  '/mars-weather': typeof MarsWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apod': typeof ApodRoute
  '/mars-rover': typeof MarsRoverRoute
  '/mars-weather': typeof MarsWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/apod' | '/mars-rover' | '/mars-weather'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/apod' | '/mars-rover' | '/mars-weather'
  id: '__root__' | '/' | '/about' | '/apod' | '/mars-rover' | '/mars-weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApodRoute: typeof ApodRoute
  MarsRoverRoute: typeof MarsRoverRoute
  MarsWeatherRoute: typeof MarsWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mars-weather': {
      id: '/mars-weather'
      path: '/mars-weather'
      fullPath: '/mars-weather'
      preLoaderRoute: typeof MarsWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mars-rover': {
      id: '/mars-rover'
      path: '/mars-rover'
      fullPath: '/mars-rover'
      preLoaderRoute: typeof MarsRoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apod': {
      id: '/apod'
      path: '/apod'
      fullPath: '/apod'
      preLoaderRoute: typeof ApodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApodRoute: ApodRoute,
  MarsRoverRoute: MarsRoverRoute,
  MarsWeatherRoute: MarsWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
