name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Lint
      working-directory: ./backend
      run: npm run lint || true  # Add this if you have a lint script

    - name: Type check
      working-directory: ./backend
      run: npm run typecheck || true  # Add this if you have a typecheck script

    - name: Run tests
      working-directory: ./backend
      run: npm test || true  # Add this if you have tests

    - name: Build
      working-directory: ./backend
      run: npm run build

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Convert github.repository to lowercase for the image tags
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        
        # Extract version from package.json
        VERSION=$(cat backend/package.json | grep '"version"' | cut -d'"' -f4)
        VERSION_TAG="v${VERSION}"
        
        # Build with multiple tags: latest, version, and version+sha for uniqueness
        docker build -t ghcr.io/${REPO_LOWER}/backend:latest \
                     -t ghcr.io/${REPO_LOWER}/backend:${VERSION_TAG} \
                     -t ghcr.io/${REPO_LOWER}/backend:${VERSION_TAG}-$(echo ${{ github.sha }} | cut -c1-7) \
                     -f backend/Dockerfile ./backend
        
        # Push all tags
        docker push ghcr.io/${REPO_LOWER}/backend:latest
        docker push ghcr.io/${REPO_LOWER}/backend:${VERSION_TAG}
        docker push ghcr.io/${REPO_LOWER}/backend:${VERSION_TAG}-$(echo ${{ github.sha }} | cut -c1-7)
        
        # Output the version for reference
        echo "Built and pushed version: ${VERSION_TAG} (from package.json v${VERSION})"
        echo "Available tags:"
        echo "  - latest"
        echo "  - ${VERSION_TAG}" 
        echo "  - ${VERSION_TAG}-$(echo ${{ github.sha }} | cut -c1-7)"
